import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "@/components/app/core/providers";
import {ThemeSwitcher} from "@/components/app/core/ThemeSwitcher";
import NavBar from "@/components/app/core/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <Providers>
        <NavBar />
        <main className="px-80">
          {children}
        </main>
        <footer>

        </footer>
      </Providers>
      </body>
    </html>
  )
}
